package persistente;
// Generated 12-feb-2019 10:59:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="Person"
    ,schema="dbo"
    ,catalog="Ejemplos"
)
public class Person  implements java.io.Serializable {


     private long id;

    public Person() {
    }

    public Person(long id) {
       this.id = id;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }




}


