package persistente;
// Generated 12-feb-2019 10:59:58 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.hibernate.annotations.NaturalId;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="Person"
    ,schema="dbo"
    ,catalog="Ejemplos"
)
public class Person  implements java.io.Serializable {

    @Id 
    @GeneratedValue
    
    @Column(name="id", unique=true, nullable=false)
    
     private long id;
    
    @NaturalId
    private String registrationNumber;
    
    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
	private List<Address> addresses = new ArrayList<>();
    public Person() {
    }

    public Person(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    public Person(long id) {
       this.id = id;
    }
   
     public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

	public void addAddress(Address address) {
		addresses.add( address );
		address.getOwners().add( this );
	}

	public void removeAddress(Address address) {
		addresses.remove( address );
		address.getOwners().remove( this );
	}

//	@Override
//	public boolean equals(Object o) {
//		if ( this == o ) {
//			return true;
//		}
//		if ( o == null || getClass() != o.getClass() ) {
//			return false;
//		}
//		Person person = (Person) o;
//		return Objects.equals( registrationNumber, person.registrationNumber );
//	}
//
//	@Override
//	public int hashCode() {
//		return Objects.hash( registrationNumber );
//	}
//

}


